import type { Preset, LossyMode } from '../../../common/types';

export const builtinPresets: Preset[] = [
  {
    id: 'preset-youtube',
    name: 'YouTube',
    description: 'Optimized for YouTube upload (H.264, AAC, 1080p)',
    category: 'builtin',
    platform: 'youtube',
    outFormat: 'mp4',
    lossyMode: {
      videoEncoder: 'libx264',
      videoPreset: 'medium',
      videoCrf: 20,
      audioEncoder: 'aac',
      audioBitrate: 192,
      audioChannels: 2,
      audioSampleRate: 44100,
      movFastStart: true,
    },
    tags: ['youtube', 'h264', 'aac'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-youtube-4k',
    name: 'YouTube 4K',
    description: 'Optimized for YouTube 4K upload (H.265, AAC, 4K)',
    category: 'builtin',
    platform: 'youtube',
    outFormat: 'mp4',
    lossyMode: {
      videoEncoder: 'libx265',
      videoPreset: 'medium',
      videoCrf: 22,
      audioEncoder: 'aac',
      audioBitrate: 384,
      audioChannels: 2,
      audioSampleRate: 48000,
      movFastStart: true,
    },
    tags: ['youtube', '4k', 'h265', 'aac'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-twitter',
    name: 'Twitter/X',
    description: 'Optimized for Twitter/X (H.264, AAC, max 512MB)',
    category: 'builtin',
    platform: 'twitter',
    outFormat: 'mp4',
    lossyMode: {
      videoEncoder: 'libx264',
      videoPreset: 'fast',
      videoCrf: 23,
      videoFilters: [
        String.raw`scale=min(1280\,iw):min(720\,ih):force_original_aspect_ratio=decrease`,
      ],
      audioEncoder: 'aac',
      audioBitrate: 128,
      audioChannels: 2,
      audioSampleRate: 44100,
      movFastStart: true,
    },
    tags: ['twitter', 'x', 'h264', 'aac'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-instagram-feed',
    name: 'Instagram Feed',
    description: 'Instagram feed post (H.264, AAC, 1:1 or 4:5)',
    category: 'builtin',
    platform: 'instagram',
    outFormat: 'mp4',
    lossyMode: {
      videoEncoder: 'libx264',
      videoPreset: 'medium',
      videoCrf: 22,
      videoFilters: [
        'scale=1080:1080:force_original_aspect_ratio=decrease,pad=1080:1080:(ow-iw)/2:(oh-ih)/2',
      ],
      audioEncoder: 'aac',
      audioBitrate: 128,
      audioChannels: 2,
      audioSampleRate: 44100,
      movFastStart: true,
    },
    tags: ['instagram', 'feed', 'square', 'h264'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-instagram-reels',
    name: 'Instagram Reels/Stories',
    description: 'Instagram Reels/Stories (H.264, AAC, 9:16 vertical)',
    category: 'builtin',
    platform: 'instagram',
    outFormat: 'mp4',
    lossyMode: {
      videoEncoder: 'libx264',
      videoPreset: 'medium',
      videoCrf: 22,
      videoFilters: [
        'scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2',
      ],
      audioEncoder: 'aac',
      audioBitrate: 128,
      audioChannels: 2,
      audioSampleRate: 44100,
      movFastStart: true,
    },
    tags: ['instagram', 'reels', 'stories', 'vertical', 'h264'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-tiktok',
    name: 'TikTok',
    description: 'TikTok optimized (H.264, AAC, 9:16 vertical, max 60s)',
    category: 'builtin',
    platform: 'tiktok',
    outFormat: 'mp4',
    lossyMode: {
      videoEncoder: 'libx264',
      videoPreset: 'fast',
      videoCrf: 22,
      videoFilters: [
        'scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2',
      ],
      audioEncoder: 'aac',
      audioBitrate: 128,
      audioChannels: 2,
      audioSampleRate: 44100,
      movFastStart: true,
    },
    tags: ['tiktok', 'vertical', 'h264'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-high-quality',
    name: 'High Quality (Archival)',
    description: 'High quality lossy encoding for archival (H.265, Opus)',
    category: 'builtin',
    platform: 'generic',
    outFormat: 'mkv',
    lossyMode: {
      videoEncoder: 'libx265',
      videoPreset: 'slow',
      videoCrf: 18,
      audioEncoder: 'libopus',
      audioBitrate: 256,
      audioChannels: 6,
      audioSampleRate: 48000,
    },
    tags: ['archival', 'high-quality', 'h265', 'opus'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-web-optimized',
    name: 'Web Optimized',
    description: 'Fast web streaming (H.264, AAC, faststart)',
    category: 'builtin',
    platform: 'generic',
    outFormat: 'mp4',
    lossyMode: {
      videoEncoder: 'libx264',
      videoPreset: 'veryfast',
      videoCrf: 23,
      audioEncoder: 'aac',
      audioBitrate: 128,
      audioChannels: 2,
      audioSampleRate: 44100,
      movFastStart: true,
    },
    tags: ['web', 'streaming', 'faststart', 'h264'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-gif-high',
    name: 'GIF High Quality',
    description: 'High quality GIF (larger file size)',
    category: 'builtin',
    platform: 'generic',
    outFormat: 'gif',
    lossyMode: {
      videoEncoder: 'libx264',
      gifFps: 15,
      gifScale: 480,
    },
    tags: ['gif', 'animation', 'high-quality'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-gif-small',
    name: 'GIF Small Size',
    description: 'Small GIF for sharing (lower quality, smaller file)',
    category: 'builtin',
    platform: 'generic',
    outFormat: 'gif',
    lossyMode: {
      videoEncoder: 'libx264',
      gifFps: 10,
      gifScale: 320,
    },
    tags: ['gif', 'animation', 'small'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-audio-mp3',
    name: 'Audio MP3',
    description: 'Extract audio as MP3 (192 kbps)',
    category: 'builtin',
    platform: 'generic',
    outFormat: 'mp3',
    lossyMode: {
      videoEncoder: 'libx264',
      audioEncoder: 'libmp3lame',
      audioBitrate: 192,
      audioChannels: 2,
      audioSampleRate: 44100,
    },
    tags: ['audio', 'mp3', 'music'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'preset-audio-opus',
    name: 'Audio Opus',
    description: 'Extract audio as Opus (128 kbps, efficient)',
    category: 'builtin',
    platform: 'generic',
    outFormat: 'opus',
    lossyMode: {
      videoEncoder: 'libx264',
      audioEncoder: 'libopus',
      audioBitrate: 128,
      audioChannels: 2,
      audioSampleRate: 48000,
    },
    tags: ['audio', 'opus', 'efficient'],
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export function getPresetById(id: string): Preset | undefined {
  return builtinPresets.find((p) => p.id === id);
}

export function getPresetsByPlatform(platform: Preset['platform']): Preset[] {
  return builtinPresets.filter((p) => p.platform === platform);
}

export function getPresetsByCategory(category: Preset['category']): Preset[] {
  return builtinPresets.filter((p) => p.category === category);
}

export function applyPresetToLossyMode(
  preset: Preset,
  currentLossyMode: LossyMode,
): LossyMode {
  return { ...currentLossyMode, ...preset.lossyMode };
}
